[2025-02-08T23:28:55.974+0000] {taskinstance.py:1083} INFO - Dependencies all met for <TaskInstance: dag_with_pythonv2.fireCrawl manual__2025-02-08T23:28:49.763137+00:00 [queued]>
[2025-02-08T23:28:56.005+0000] {taskinstance.py:1083} INFO - Dependencies all met for <TaskInstance: dag_with_pythonv2.fireCrawl manual__2025-02-08T23:28:49.763137+00:00 [queued]>
[2025-02-08T23:28:56.006+0000] {taskinstance.py:1279} INFO - 
--------------------------------------------------------------------------------
[2025-02-08T23:28:56.006+0000] {taskinstance.py:1280} INFO - Starting attempt 1 of 1
[2025-02-08T23:28:56.006+0000] {taskinstance.py:1281} INFO - 
--------------------------------------------------------------------------------
[2025-02-08T23:28:56.042+0000] {taskinstance.py:1300} INFO - Executing <Task(PythonOperator): fireCrawl> on 2025-02-08 23:28:49.763137+00:00
[2025-02-08T23:28:56.053+0000] {standard_task_runner.py:55} INFO - Started process 2157 to run task
[2025-02-08T23:28:56.058+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'dag_with_pythonv2', 'fireCrawl', 'manual__2025-02-08T23:28:49.763137+00:00', '--job-id', '38', '--raw', '--subdir', 'DAGS_FOLDER/test.py', '--cfg-path', '/tmp/tmprzj_zgui']
[2025-02-08T23:28:56.059+0000] {standard_task_runner.py:83} INFO - Job 38: Subtask fireCrawl
[2025-02-08T23:28:56.158+0000] {task_command.py:388} INFO - Running <TaskInstance: dag_with_pythonv2.fireCrawl manual__2025-02-08T23:28:49.763137+00:00 [running]> on host 1694b062ea20
[2025-02-08T23:28:56.280+0000] {taskinstance.py:1509} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=dag_with_pythonv2
AIRFLOW_CTX_TASK_ID=fireCrawl
AIRFLOW_CTX_EXECUTION_DATE=2025-02-08T23:28:49.763137+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2025-02-08T23:28:49.763137+00:00
[2025-02-08T23:28:59.426+0000] {taskinstance.py:1768} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 175, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 192, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/test.py", line 24, in get_links
    zip_links = [link for link in response['links'] if link.endswith('.zip')]
KeyError: 'links'
[2025-02-08T23:28:59.991+0000] {taskinstance.py:1323} INFO - Marking task as FAILED. dag_id=dag_with_pythonv2, task_id=fireCrawl, execution_date=20250208T232849, start_date=20250208T232855, end_date=20250208T232859
[2025-02-08T23:29:00.074+0000] {standard_task_runner.py:105} ERROR - Failed to execute job 38 for task fireCrawl ('links'; 2157)
[2025-02-08T23:29:00.131+0000] {local_task_job.py:208} INFO - Task exited with return code 1
[2025-02-08T23:29:00.182+0000] {taskinstance.py:2578} INFO - 0 downstream tasks scheduled from follow-on schedule check
