[2025-02-12T19:22:26.836+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-02-12T19:22:26.850+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: dag_for_dbt_raw.Check_if_data_exists manual__2025-02-12T14:22:20-05:00 [queued]>
[2025-02-12T19:22:26.859+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: dag_for_dbt_raw.Check_if_data_exists manual__2025-02-12T14:22:20-05:00 [queued]>
[2025-02-12T19:22:26.859+0000] {taskinstance.py:2866} INFO - Starting attempt 1 of 1
[2025-02-12T19:22:26.872+0000] {taskinstance.py:2889} INFO - Executing <Task(BranchPythonOperator): Check_if_data_exists> on 2025-02-12 19:22:20+00:00
[2025-02-12T19:22:26.877+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=854) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-02-12T19:22:26.878+0000] {standard_task_runner.py:72} INFO - Started process 855 to run task
[2025-02-12T19:22:26.879+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'dag_for_dbt_raw', 'Check_if_data_exists', 'manual__2025-02-12T14:22:20-05:00', '--job-id', '212', '--raw', '--subdir', 'DAGS_FOLDER/dbt_raw_dag.py', '--cfg-path', '/tmp/tmpwlqyvtwm']
[2025-02-12T19:22:26.880+0000] {standard_task_runner.py:105} INFO - Job 212: Subtask Check_if_data_exists
[2025-02-12T19:22:26.934+0000] {task_command.py:467} INFO - Running <TaskInstance: dag_for_dbt_raw.Check_if_data_exists manual__2025-02-12T14:22:20-05:00 [running]> on host e73c0d3ecbea
[2025-02-12T19:22:27.021+0000] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='dag_for_dbt_raw' AIRFLOW_CTX_TASK_ID='Check_if_data_exists' AIRFLOW_CTX_EXECUTION_DATE='2025-02-12T19:22:20+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-02-12T14:22:20-05:00'
[2025-02-12T19:22:27.022+0000] {taskinstance.py:731} INFO - ::endgroup::
[2025-02-12T19:22:27.035+0000] {baseoperator.py:421} WARNING - BranchPythonOperator.execute cannot be called outside TaskInstance!
[2025-02-12T19:22:27.064+0000] {logging_mixin.py:190} INFO - Pushing to XCom - Year: 2024, Quarter: 4
[2025-02-12T19:22:27.416+0000] {python.py:240} INFO - Done. Returned value was: dbt_curl_command
[2025-02-12T19:22:27.417+0000] {branch.py:38} INFO - Branch into dbt_curl_command
[2025-02-12T19:22:27.417+0000] {skipmixin.py:230} INFO - Following branch ('dbt_curl_command',)
[2025-02-12T19:22:27.429+0000] {skipmixin.py:278} INFO - Skipping tasks [('Upload_data_to_s3', -1)]
[2025-02-12T19:22:27.462+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2025-02-12T19:22:27.463+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=dag_for_dbt_raw, task_id=Check_if_data_exists, run_id=manual__2025-02-12T14:22:20-05:00, execution_date=20250212T192220, start_date=20250212T192226, end_date=20250212T192227
[2025-02-12T19:22:27.495+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-02-12T19:22:27.525+0000] {taskinstance.py:3895} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-02-12T19:22:27.530+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
