[2025-02-08T23:11:59.784+0000] {taskinstance.py:1083} INFO - Dependencies all met for <TaskInstance: dag_with_pythonv2.fireCrawl manual__2025-02-08T23:11:55.023320+00:00 [queued]>
[2025-02-08T23:11:59.800+0000] {taskinstance.py:1083} INFO - Dependencies all met for <TaskInstance: dag_with_pythonv2.fireCrawl manual__2025-02-08T23:11:55.023320+00:00 [queued]>
[2025-02-08T23:11:59.800+0000] {taskinstance.py:1279} INFO - 
--------------------------------------------------------------------------------
[2025-02-08T23:11:59.801+0000] {taskinstance.py:1280} INFO - Starting attempt 1 of 1
[2025-02-08T23:11:59.801+0000] {taskinstance.py:1281} INFO - 
--------------------------------------------------------------------------------
[2025-02-08T23:11:59.821+0000] {taskinstance.py:1300} INFO - Executing <Task(PythonOperator): fireCrawl> on 2025-02-08 23:11:55.023320+00:00
[2025-02-08T23:11:59.829+0000] {standard_task_runner.py:55} INFO - Started process 830 to run task
[2025-02-08T23:11:59.833+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'dag_with_pythonv2', 'fireCrawl', 'manual__2025-02-08T23:11:55.023320+00:00', '--job-id', '30', '--raw', '--subdir', 'DAGS_FOLDER/test.py', '--cfg-path', '/tmp/tmprvuj9mt5']
[2025-02-08T23:11:59.834+0000] {standard_task_runner.py:83} INFO - Job 30: Subtask fireCrawl
[2025-02-08T23:11:59.956+0000] {task_command.py:388} INFO - Running <TaskInstance: dag_with_pythonv2.fireCrawl manual__2025-02-08T23:11:55.023320+00:00 [running]> on host 1694b062ea20
[2025-02-08T23:12:00.105+0000] {taskinstance.py:1509} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=dag_with_pythonv2
AIRFLOW_CTX_TASK_ID=fireCrawl
AIRFLOW_CTX_EXECUTION_DATE=2025-02-08T23:11:55.023320+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2025-02-08T23:11:55.023320+00:00
[2025-02-08T23:12:02.586+0000] {taskinstance.py:1768} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 175, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 192, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/test.py", line 27, in get_links
    all_links = response['links']
KeyError: 'links'
[2025-02-08T23:12:02.634+0000] {taskinstance.py:1323} INFO - Marking task as FAILED. dag_id=dag_with_pythonv2, task_id=fireCrawl, execution_date=20250208T231155, start_date=20250208T231159, end_date=20250208T231202
[2025-02-08T23:12:02.661+0000] {standard_task_runner.py:105} ERROR - Failed to execute job 30 for task fireCrawl ('links'; 830)
[2025-02-08T23:12:02.683+0000] {local_task_job.py:208} INFO - Task exited with return code 1
[2025-02-08T23:12:02.707+0000] {taskinstance.py:2578} INFO - 0 downstream tasks scheduled from follow-on schedule check
