[2025-02-09T08:21:44.904+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-02-09T08:21:44.930+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: dag_to_scrape_and_upload.Upload_data_to_s3 manual__2025-02-09T08:21:42.298698+00:00 [queued]>
[2025-02-09T08:21:44.944+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: dag_to_scrape_and_upload.Upload_data_to_s3 manual__2025-02-09T08:21:42.298698+00:00 [queued]>
[2025-02-09T08:21:44.945+0000] {taskinstance.py:2866} INFO - Starting attempt 1 of 1
[2025-02-09T08:21:44.963+0000] {taskinstance.py:2889} INFO - Executing <Task(PythonOperator): Upload_data_to_s3> on 2025-02-09 08:21:42.298698+00:00
[2025-02-09T08:21:44.969+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=365) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-02-09T08:21:44.972+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'dag_to_scrape_and_upload', 'Upload_data_to_s3', 'manual__2025-02-09T08:21:42.298698+00:00', '--job-id', '45', '--raw', '--subdir', 'DAGS_FOLDER/scrape_upload_dag.py', '--cfg-path', '/tmp/tmpnp97vbnd']
[2025-02-09T08:21:44.973+0000] {standard_task_runner.py:72} INFO - Started process 373 to run task
[2025-02-09T08:21:44.974+0000] {standard_task_runner.py:105} INFO - Job 45: Subtask Upload_data_to_s3
[2025-02-09T08:21:45.033+0000] {task_command.py:467} INFO - Running <TaskInstance: dag_to_scrape_and_upload.Upload_data_to_s3 manual__2025-02-09T08:21:42.298698+00:00 [running]> on host baad8f7d3b7c
[2025-02-09T08:21:45.150+0000] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='dag_to_scrape_and_upload' AIRFLOW_CTX_TASK_ID='Upload_data_to_s3' AIRFLOW_CTX_EXECUTION_DATE='2025-02-09T08:21:42.298698+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-02-09T08:21:42.298698+00:00'
[2025-02-09T08:21:45.151+0000] {taskinstance.py:731} INFO - ::endgroup::
[2025-02-09T08:21:53.003+0000] {logging_mixin.py:190} INFO - uploaded file sub.txt
[2025-02-09T08:22:11.382+0000] {job.py:229} INFO - Heartbeat recovered after 15.99 seconds
[2025-02-09T08:22:41.812+0000] {local_task_job_runner.py:318} WARNING - Recorded pid 383 does not match the current pid 373
[2025-02-09T08:22:41.819+0000] {local_task_job_runner.py:218} WARNING - Heartbeat failed with Exception: PID of job runner does not match
[2025-02-09T08:22:46.992+0000] {local_task_job_runner.py:318} WARNING - Recorded pid 383 does not match the current pid 373
[2025-02-09T08:22:46.993+0000] {local_task_job_runner.py:218} WARNING - Heartbeat failed with Exception: PID of job runner does not match
[2025-02-09T08:22:51.857+0000] {logging_mixin.py:190} INFO - uploaded file pre.txt
[2025-02-09T08:22:52.027+0000] {local_task_job_runner.py:318} WARNING - Recorded pid 383 does not match the current pid 373
[2025-02-09T08:22:52.028+0000] {local_task_job_runner.py:218} WARNING - Heartbeat failed with Exception: PID of job runner does not match
[2025-02-09T08:22:55.015+0000] {local_task_job_runner.py:266} INFO - Task exited with return code -9. For more information, see https://***.apache.org/docs/apache-***/stable/troubleshooting.html#LocalTaskJob-killed
[2025-02-09T08:22:55.173+0000] {standard_task_runner.py:217} INFO - Process not found (most likely exited), stop collecting metrics
[2025-02-09T08:22:55.541+0000] {taskinstance.py:3895} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-02-09T08:22:55.543+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
