[2025-02-12T19:13:43.023+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-02-12T19:13:43.040+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: dag_for_dbt_raw.Check_if_data_exists manual__2025-02-12T14:13:18-05:00 [queued]>
[2025-02-12T19:13:43.048+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: dag_for_dbt_raw.Check_if_data_exists manual__2025-02-12T14:13:18-05:00 [queued]>
[2025-02-12T19:13:43.048+0000] {taskinstance.py:2866} INFO - Starting attempt 1 of 1
[2025-02-12T19:13:43.064+0000] {taskinstance.py:2889} INFO - Executing <Task(BranchPythonOperator): Check_if_data_exists> on 2025-02-12 19:13:18+00:00
[2025-02-12T19:13:43.069+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=699) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-02-12T19:13:43.070+0000] {standard_task_runner.py:72} INFO - Started process 700 to run task
[2025-02-12T19:13:43.072+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'dag_for_dbt_raw', 'Check_if_data_exists', 'manual__2025-02-12T14:13:18-05:00', '--job-id', '202', '--raw', '--subdir', 'DAGS_FOLDER/dbt_raw_dag.py', '--cfg-path', '/tmp/tmp1ymda7sq']
[2025-02-12T19:13:43.073+0000] {standard_task_runner.py:105} INFO - Job 202: Subtask Check_if_data_exists
[2025-02-12T19:13:43.118+0000] {task_command.py:467} INFO - Running <TaskInstance: dag_for_dbt_raw.Check_if_data_exists manual__2025-02-12T14:13:18-05:00 [running]> on host e73c0d3ecbea
[2025-02-12T19:13:43.197+0000] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='dag_for_dbt_raw' AIRFLOW_CTX_TASK_ID='Check_if_data_exists' AIRFLOW_CTX_EXECUTION_DATE='2025-02-12T19:13:18+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-02-12T14:13:18-05:00'
[2025-02-12T19:13:43.198+0000] {taskinstance.py:731} INFO - ::endgroup::
[2025-02-12T19:13:43.209+0000] {baseoperator.py:421} WARNING - BranchPythonOperator.execute cannot be called outside TaskInstance!
[2025-02-12T19:13:43.234+0000] {logging_mixin.py:190} INFO - Pushing to XCom - Year: 2024, Quarter: 4
[2025-02-12T19:13:43.606+0000] {python.py:240} INFO - Done. Returned value was: dbt_raw
[2025-02-12T19:13:43.608+0000] {branch.py:38} INFO - Branch into dbt_raw
[2025-02-12T19:13:43.608+0000] {skipmixin.py:230} INFO - Following branch ('dbt_raw',)
[2025-02-12T19:13:43.618+0000] {taskinstance.py:3311} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 422, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 274, in execute
    return self.do_branch(context, super().execute(context))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/branch.py", line 40, in do_branch
    self.skip_all_except(context["ti"], branch_task_ids)
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/skipmixin.py", line 189, in skip_all_except
    SkipMixin._skip_all_except(ti=ti, branch_task_ids=branch_task_ids)
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/api_internal/internal_api_call.py", line 166, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/skipmixin.py", line 243, in _skip_all_except
    raise AirflowException(
airflow.exceptions.AirflowException: 'branch_task_ids' must contain only valid task_ids. Invalid tasks found: {'dbt_raw'}.
[2025-02-12T19:13:43.631+0000] {taskinstance.py:1225} INFO - Marking task as FAILED. dag_id=dag_for_dbt_raw, task_id=Check_if_data_exists, run_id=manual__2025-02-12T14:13:18-05:00, execution_date=20250212T191318, start_date=20250212T191343, end_date=20250212T191343
[2025-02-12T19:13:43.647+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2025-02-12T19:13:43.648+0000] {standard_task_runner.py:124} ERROR - Failed to execute job 202 for task Check_if_data_exists ('branch_task_ids' must contain only valid task_ids. Invalid tasks found: {'dbt_raw'}.; 700)
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/cli.py", line 116, in wrapper
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
           ^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3005, in _run_raw_task
    return _run_raw_task(
           ^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 273, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3159, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3183, in _execute_task
    return _execute_task(self, context, task_orig)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 422, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 274, in execute
    return self.do_branch(context, super().execute(context))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/branch.py", line 40, in do_branch
    self.skip_all_except(context["ti"], branch_task_ids)
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/skipmixin.py", line 189, in skip_all_except
    SkipMixin._skip_all_except(ti=ti, branch_task_ids=branch_task_ids)
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/api_internal/internal_api_call.py", line 166, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/skipmixin.py", line 243, in _skip_all_except
    raise AirflowException(
airflow.exceptions.AirflowException: 'branch_task_ids' must contain only valid task_ids. Invalid tasks found: {'dbt_raw'}.
[2025-02-12T19:13:43.689+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 1
[2025-02-12T19:13:43.718+0000] {taskinstance.py:3895} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-02-12T19:13:43.725+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
