[2025-02-13T03:45:14.069+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-02-13T03:45:14.097+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: dag_for_dbt_json.Upload_data_to_s3 manual__2025-02-12T22:44:51-05:00 [queued]>
[2025-02-13T03:45:14.111+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: dag_for_dbt_json.Upload_data_to_s3 manual__2025-02-12T22:44:51-05:00 [queued]>
[2025-02-13T03:45:14.111+0000] {taskinstance.py:2866} INFO - Starting attempt 1 of 1
[2025-02-13T03:45:14.128+0000] {taskinstance.py:2889} INFO - Executing <Task(PythonOperator): Upload_data_to_s3> on 2025-02-13 03:44:51+00:00
[2025-02-13T03:45:14.133+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=1886) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-02-13T03:45:14.136+0000] {standard_task_runner.py:72} INFO - Started process 1892 to run task
[2025-02-13T03:45:14.136+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'dag_for_dbt_json', 'Upload_data_to_s3', 'manual__2025-02-12T22:44:51-05:00', '--job-id', '265', '--raw', '--subdir', 'DAGS_FOLDER/json_dag.py', '--cfg-path', '/tmp/tmpylbvt7jl']
[2025-02-13T03:45:14.137+0000] {standard_task_runner.py:105} INFO - Job 265: Subtask Upload_data_to_s3
[2025-02-13T03:45:14.182+0000] {task_command.py:467} INFO - Running <TaskInstance: dag_for_dbt_json.Upload_data_to_s3 manual__2025-02-12T22:44:51-05:00 [running]> on host f917fd63a571
[2025-02-13T03:45:14.288+0000] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='dag_for_dbt_json' AIRFLOW_CTX_TASK_ID='Upload_data_to_s3' AIRFLOW_CTX_EXECUTION_DATE='2025-02-13T03:44:51+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-02-12T22:44:51-05:00'
[2025-02-13T03:45:14.290+0000] {taskinstance.py:731} INFO - ::endgroup::
[2025-02-13T03:45:23.417+0000] {logging_mixin.py:190} INFO - uploaded file sub.txt
[2025-02-13T03:45:54.650+0000] {logging_mixin.py:190} INFO - uploaded file pre.txt
[2025-02-13T03:47:15.861+0000] {local_task_job_runner.py:346} WARNING - State of this instance has been externally set to restarting. Terminating instance.
[2025-02-13T03:47:15.906+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
[2025-02-13T03:47:15.929+0000] {process_utils.py:132} INFO - Sending 15 to group 1892. PIDs of all processes in the group: [1892]
[2025-02-13T03:47:15.932+0000] {process_utils.py:87} INFO - Sending the signal 15 to group 1892
[2025-02-13T03:47:15.944+0000] {taskinstance.py:3093} ERROR - Received SIGTERM. Terminating subprocesses.
[2025-02-13T03:47:19.386+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2025-02-13T03:47:19.528+0000] {process_utils.py:80} INFO - Process psutil.Process(pid=1892, status='terminated', exitcode=0, started='03:45:13') (1892) terminated with exit code 0
