[2025-02-12T19:17:50.045+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-02-12T19:17:50.061+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: dag_for_dbt_raw.Check_if_data_exists manual__2025-02-12T14:17:43-05:00 [queued]>
[2025-02-12T19:17:50.072+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: dag_for_dbt_raw.Check_if_data_exists manual__2025-02-12T14:17:43-05:00 [queued]>
[2025-02-12T19:17:50.073+0000] {taskinstance.py:2866} INFO - Starting attempt 1 of 1
[2025-02-12T19:17:50.088+0000] {taskinstance.py:2889} INFO - Executing <Task(BranchPythonOperator): Check_if_data_exists> on 2025-02-12 19:17:43+00:00
[2025-02-12T19:17:50.093+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=769) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-02-12T19:17:50.095+0000] {standard_task_runner.py:72} INFO - Started process 770 to run task
[2025-02-12T19:17:50.095+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'dag_for_dbt_raw', 'Check_if_data_exists', 'manual__2025-02-12T14:17:43-05:00', '--job-id', '206', '--raw', '--subdir', 'DAGS_FOLDER/dbt_raw_dag.py', '--cfg-path', '/tmp/tmp21_9n9ri']
[2025-02-12T19:17:50.099+0000] {standard_task_runner.py:105} INFO - Job 206: Subtask Check_if_data_exists
[2025-02-12T19:17:50.149+0000] {task_command.py:467} INFO - Running <TaskInstance: dag_for_dbt_raw.Check_if_data_exists manual__2025-02-12T14:17:43-05:00 [running]> on host e73c0d3ecbea
[2025-02-12T19:17:50.227+0000] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='dag_for_dbt_raw' AIRFLOW_CTX_TASK_ID='Check_if_data_exists' AIRFLOW_CTX_EXECUTION_DATE='2025-02-12T19:17:43+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-02-12T14:17:43-05:00'
[2025-02-12T19:17:50.228+0000] {taskinstance.py:731} INFO - ::endgroup::
[2025-02-12T19:17:50.240+0000] {baseoperator.py:421} WARNING - BranchPythonOperator.execute cannot be called outside TaskInstance!
[2025-02-12T19:17:50.268+0000] {logging_mixin.py:190} INFO - Pushing to XCom - Year: 2024, Quarter: 4
[2025-02-12T19:17:50.634+0000] {python.py:240} INFO - Done. Returned value was: dbt_curl_command
[2025-02-12T19:17:50.635+0000] {branch.py:38} INFO - Branch into dbt_curl_command
[2025-02-12T19:17:50.636+0000] {skipmixin.py:230} INFO - Following branch ('dbt_curl_command',)
[2025-02-12T19:17:50.644+0000] {skipmixin.py:278} INFO - Skipping tasks [('Upload_data_to_s3', -1)]
[2025-02-12T19:17:50.670+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2025-02-12T19:17:50.671+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=dag_for_dbt_raw, task_id=Check_if_data_exists, run_id=manual__2025-02-12T14:17:43-05:00, execution_date=20250212T191743, start_date=20250212T191750, end_date=20250212T191750
[2025-02-12T19:17:50.716+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-02-12T19:17:50.739+0000] {taskinstance.py:3895} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-02-12T19:17:50.744+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
