[2025-02-12T00:00:03.799+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-02-12T00:00:03.823+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: dag_to_scrape_and_upload.Upload_data_to_s3 scheduled__2025-02-11T00:00:00+00:00 [queued]>
[2025-02-12T00:00:03.836+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: dag_to_scrape_and_upload.Upload_data_to_s3 scheduled__2025-02-11T00:00:00+00:00 [queued]>
[2025-02-12T00:00:03.837+0000] {taskinstance.py:2866} INFO - Starting attempt 1 of 1
[2025-02-12T00:00:03.858+0000] {taskinstance.py:2889} INFO - Executing <Task(PythonOperator): Upload_data_to_s3> on 2025-02-11 00:00:00+00:00
[2025-02-12T00:00:03.864+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=279) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-02-12T00:00:03.867+0000] {standard_task_runner.py:72} INFO - Started process 280 to run task
[2025-02-12T00:00:03.867+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'dag_to_scrape_and_upload', 'Upload_data_to_s3', 'scheduled__2025-02-11T00:00:00+00:00', '--job-id', '144', '--raw', '--subdir', 'DAGS_FOLDER/scrape_upload_dag.py', '--cfg-path', '/tmp/tmp_r_eqq1q']
[2025-02-12T00:00:03.869+0000] {standard_task_runner.py:105} INFO - Job 144: Subtask Upload_data_to_s3
[2025-02-12T00:00:03.924+0000] {task_command.py:467} INFO - Running <TaskInstance: dag_to_scrape_and_upload.Upload_data_to_s3 scheduled__2025-02-11T00:00:00+00:00 [running]> on host ecdf8258250e
[2025-02-12T00:00:04.034+0000] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='dag_to_scrape_and_upload' AIRFLOW_CTX_TASK_ID='Upload_data_to_s3' AIRFLOW_CTX_EXECUTION_DATE='2025-02-11T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-02-11T00:00:00+00:00'
[2025-02-12T00:00:04.035+0000] {taskinstance.py:731} INFO - ::endgroup::
[2025-02-12T00:00:20.966+0000] {logging_mixin.py:190} INFO - uploaded file sub.txt
[2025-02-12T00:00:36.538+0000] {logging_mixin.py:190} INFO - uploaded file pre.txt
[2025-02-12T00:01:49.839+0000] {local_task_job_runner.py:346} WARNING - State of this instance has been externally set to removed. Terminating instance.
[2025-02-12T00:01:49.852+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
[2025-02-12T00:01:49.867+0000] {process_utils.py:132} INFO - Sending 15 to group 280. PIDs of all processes in the group: [280]
[2025-02-12T00:01:49.870+0000] {process_utils.py:87} INFO - Sending the signal 15 to group 280
[2025-02-12T00:01:49.874+0000] {taskinstance.py:3093} ERROR - Received SIGTERM. Terminating subprocesses.
[2025-02-12T00:01:50.307+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2025-02-12T00:01:50.367+0000] {process_utils.py:80} INFO - Process psutil.Process(pid=280, status='terminated', exitcode=0, started='00:00:03') (280) terminated with exit code 0
