[2025-02-14T02:23:53.841+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-02-14T02:23:53.868+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: dag_for_dbt_denormalize.Check_if_data_exists manual__2025-02-13T21:23:44-05:00 [queued]>
[2025-02-14T02:23:53.881+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: dag_for_dbt_denormalize.Check_if_data_exists manual__2025-02-13T21:23:44-05:00 [queued]>
[2025-02-14T02:23:53.882+0000] {taskinstance.py:2866} INFO - Starting attempt 1 of 1
[2025-02-14T02:23:53.902+0000] {taskinstance.py:2889} INFO - Executing <Task(BranchPythonOperator): Check_if_data_exists> on 2025-02-14 02:23:44+00:00
[2025-02-14T02:23:53.910+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=168) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-02-14T02:23:53.912+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'dag_for_dbt_denormalize', 'Check_if_data_exists', 'manual__2025-02-13T21:23:44-05:00', '--job-id', '323', '--raw', '--subdir', 'DAGS_FOLDER/denormalize_data_gad.py', '--cfg-path', '/tmp/tmpnymuw8b_']
[2025-02-14T02:23:53.914+0000] {standard_task_runner.py:72} INFO - Started process 169 to run task
[2025-02-14T02:23:53.914+0000] {standard_task_runner.py:105} INFO - Job 323: Subtask Check_if_data_exists
[2025-02-14T02:23:53.966+0000] {task_command.py:467} INFO - Running <TaskInstance: dag_for_dbt_denormalize.Check_if_data_exists manual__2025-02-13T21:23:44-05:00 [running]> on host 520ef09c550f
[2025-02-14T02:23:54.079+0000] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='dag_for_dbt_denormalize' AIRFLOW_CTX_TASK_ID='Check_if_data_exists' AIRFLOW_CTX_EXECUTION_DATE='2025-02-14T02:23:44+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-02-13T21:23:44-05:00'
[2025-02-14T02:23:54.081+0000] {taskinstance.py:731} INFO - ::endgroup::
[2025-02-14T02:23:54.106+0000] {baseoperator.py:421} WARNING - BranchPythonOperator.execute cannot be called outside TaskInstance!
[2025-02-14T02:23:54.748+0000] {python.py:240} INFO - Done. Returned value was: Upload_data_to_s3
[2025-02-14T02:23:54.751+0000] {branch.py:38} INFO - Branch into Upload_data_to_s3
[2025-02-14T02:23:54.752+0000] {skipmixin.py:230} INFO - Following branch ('Upload_data_to_s3',)
[2025-02-14T02:23:54.765+0000] {skipmixin.py:278} INFO - Skipping tasks []
[2025-02-14T02:23:54.801+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2025-02-14T02:23:54.802+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=dag_for_dbt_denormalize, task_id=Check_if_data_exists, run_id=manual__2025-02-13T21:23:44-05:00, execution_date=20250214T022344, start_date=20250214T022353, end_date=20250214T022354
[2025-02-14T02:23:54.851+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-02-14T02:23:54.891+0000] {taskinstance.py:3895} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2025-02-14T02:23:54.894+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
