[2025-02-12T18:55:29.744+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-02-12T18:55:29.763+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: dag_for_dbt_json.Check_if_data_exists manual__2025-02-12T13:55:23-05:00 [queued]>
[2025-02-12T18:55:29.772+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: dag_for_dbt_json.Check_if_data_exists manual__2025-02-12T13:55:23-05:00 [queued]>
[2025-02-12T18:55:29.773+0000] {taskinstance.py:2866} INFO - Starting attempt 1 of 1
[2025-02-12T18:55:29.788+0000] {taskinstance.py:2889} INFO - Executing <Task(BranchPythonOperator): Check_if_data_exists> on 2025-02-12 18:55:23+00:00
[2025-02-12T18:55:29.793+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=441) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-02-12T18:55:29.795+0000] {standard_task_runner.py:72} INFO - Started process 443 to run task
[2025-02-12T18:55:29.795+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'dag_for_dbt_json', 'Check_if_data_exists', 'manual__2025-02-12T13:55:23-05:00', '--job-id', '195', '--raw', '--subdir', 'DAGS_FOLDER/json_dag.py', '--cfg-path', '/tmp/tmpd_x8626r']
[2025-02-12T18:55:29.796+0000] {standard_task_runner.py:105} INFO - Job 195: Subtask Check_if_data_exists
[2025-02-12T18:55:29.840+0000] {task_command.py:467} INFO - Running <TaskInstance: dag_for_dbt_json.Check_if_data_exists manual__2025-02-12T13:55:23-05:00 [running]> on host e73c0d3ecbea
[2025-02-12T18:55:29.916+0000] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='dag_for_dbt_json' AIRFLOW_CTX_TASK_ID='Check_if_data_exists' AIRFLOW_CTX_EXECUTION_DATE='2025-02-12T18:55:23+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-02-12T13:55:23-05:00'
[2025-02-12T18:55:29.918+0000] {taskinstance.py:731} INFO - ::endgroup::
[2025-02-12T18:55:29.930+0000] {baseoperator.py:421} WARNING - BranchPythonOperator.execute cannot be called outside TaskInstance!
[2025-02-12T18:55:29.952+0000] {logging_mixin.py:190} INFO - Pushing to XCom - Year: 2024, Quarter: 4
[2025-02-12T18:55:30.278+0000] {python.py:240} INFO - Done. Returned value was: dbt_curl_command
[2025-02-12T18:55:30.279+0000] {branch.py:38} INFO - Branch into dbt_curl_command
[2025-02-12T18:55:30.280+0000] {skipmixin.py:230} INFO - Following branch ('dbt_curl_command',)
[2025-02-12T18:55:30.289+0000] {skipmixin.py:278} INFO - Skipping tasks [('Upload_data_to_s3', -1)]
[2025-02-12T18:55:30.319+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2025-02-12T18:55:30.320+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=dag_for_dbt_json, task_id=Check_if_data_exists, run_id=manual__2025-02-12T13:55:23-05:00, execution_date=20250212T185523, start_date=20250212T185529, end_date=20250212T185530
[2025-02-12T18:55:30.372+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-02-12T18:55:30.397+0000] {taskinstance.py:3895} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-02-12T18:55:30.403+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
