[2025-02-13T01:49:20.387+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-02-13T01:49:20.415+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: dag_for_dbt_json.Check_if_data_exists manual__2025-02-12T20:49:13-05:00 [queued]>
[2025-02-13T01:49:20.435+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: dag_for_dbt_json.Check_if_data_exists manual__2025-02-12T20:49:13-05:00 [queued]>
[2025-02-13T01:49:20.436+0000] {taskinstance.py:2866} INFO - Starting attempt 1 of 1
[2025-02-13T01:49:20.471+0000] {taskinstance.py:2889} INFO - Executing <Task(BranchPythonOperator): Check_if_data_exists> on 2025-02-13 01:49:13+00:00
[2025-02-13T01:49:20.483+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=1055) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-02-13T01:49:20.485+0000] {standard_task_runner.py:72} INFO - Started process 1056 to run task
[2025-02-13T01:49:20.486+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'dag_for_dbt_json', 'Check_if_data_exists', 'manual__2025-02-12T20:49:13-05:00', '--job-id', '247', '--raw', '--subdir', 'DAGS_FOLDER/json_dag.py', '--cfg-path', '/tmp/tmpwtto86uf']
[2025-02-13T01:49:20.487+0000] {standard_task_runner.py:105} INFO - Job 247: Subtask Check_if_data_exists
[2025-02-13T01:49:20.557+0000] {task_command.py:467} INFO - Running <TaskInstance: dag_for_dbt_json.Check_if_data_exists manual__2025-02-12T20:49:13-05:00 [running]> on host f917fd63a571
[2025-02-13T01:49:20.668+0000] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='dag_for_dbt_json' AIRFLOW_CTX_TASK_ID='Check_if_data_exists' AIRFLOW_CTX_EXECUTION_DATE='2025-02-13T01:49:13+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-02-12T20:49:13-05:00'
[2025-02-13T01:49:20.669+0000] {taskinstance.py:731} INFO - ::endgroup::
[2025-02-13T01:49:20.689+0000] {baseoperator.py:421} WARNING - BranchPythonOperator.execute cannot be called outside TaskInstance!
[2025-02-13T01:49:21.309+0000] {python.py:240} INFO - Done. Returned value was: dbt_curl_command
[2025-02-13T01:49:21.314+0000] {branch.py:38} INFO - Branch into dbt_curl_command
[2025-02-13T01:49:21.316+0000] {skipmixin.py:230} INFO - Following branch ('dbt_curl_command',)
[2025-02-13T01:49:21.332+0000] {skipmixin.py:278} INFO - Skipping tasks [('Upload_data_to_s3', -1)]
[2025-02-13T01:49:21.384+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2025-02-13T01:49:21.386+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=dag_for_dbt_json, task_id=Check_if_data_exists, run_id=manual__2025-02-12T20:49:13-05:00, execution_date=20250213T014913, start_date=20250213T014920, end_date=20250213T014921
[2025-02-13T01:49:21.430+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-02-13T01:49:21.469+0000] {taskinstance.py:3895} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2025-02-13T01:49:21.475+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
